window.igBios = [
  "💖 Love Life 💖",
  "😎 Swag Mode 😎",
  "🌟 Dream Big 🌟",
  "🔥 Keep Fighting 🔥",
  "🧠 Mindset Strong 🧠",
  "🌈 Be Yourself 🌈",
  "💎 Shine Bright 💎",
  "⚡ Fast & Furious ⚡",
  "🦁 King Attitude 🦁",
  "🎵 Music Lover 🎵",
  // --- 😎 ATTITUDE (Name Based) ---
  "🔥 {name} Ka Ilaaka, Dhamaka Pakka! 👑",
  "🤙 Sun Beta, {name} Naam Hi Kaafi Hai! 🔫",
  "🦁 Sher Ki Dahaad Aur {name} Ka Andaaz, Alag Hai!",
  "🚫 Don't Copy My Style, I'm {name}! ✨",
  "🕶️ {name}: Attitude Toh Bachpan Se Hai! 😎",
  "🚀 Sky Is The Limit, But {name} Is Beyond! 🌌",
  "💯 Rule No. 1: Never Forget {name}! 🔥",
  "💸 Shauk Nahi, Brand Hoon Main: {name} 💎",
  "🦁 {name} – Raj toh hum har jagah karte hain!",
  "👊 Dushmano Ke Liye Kaafi Hai {name} Ka Naam!",

  // --- ❤️ LOVE & ROMANTIC ---
  "🥀 {name} + Teri Muskurahat = My Life! ❤️",
  "✨ Har Dua Mein Shamil Hai Naam Tera... {name} 🙏",
  "💘 {name}: Dil Ka Raaja, Teri Yaad Mein Paagal!",
  "🌍 My World Starts And Ends With You... - {name}",
  "🌹 {name}: Ishq Ka Maara, Dil Se Pyaara!",
  "🦋 {name} - Teri Aankhon Mein Hi Meri Jannat Hai!",
  "💖 Only For You... Yours {name}!",
  "🌈 {name}: Zindagi Khoobsurat Hai Tumhare Saath!",

  // --- 🎭 SHAYARI & LINES ---
  "✍️ {name}: Likhta Hoon Dil Se, Padhte Hain Log Shauk Se!",
  "📖 {name}: Ek Adhoori Kahani Ka Poora Kissa!",
  "🕯️ Miloge Hamari Tarah, Toh Yaad Karoge... - {name}",
  "🌊 Samundar Sa Jigar Rakhta Hai {name}!",
  "🥀 {name}: Kuch Zakhm Sirf Khamoshi Se Bharte Hain!",
  "🎭 Kirdaar Aisa Ki Duniya Yaad Rakhe... {name}",
  "🚶‍♂️ {name}: Tanha Magar Apni Dhun Mein Mast!",

  // --- 💔 SAD & BROKEN ---
  "🌑 {name}: Khamosh Raatein Aur Teri Yaadein...",
  "💔 Broken But Still {name}... 🥀",
  "🚶‍♂️ Akela Chalna Seekh Liya Hai... - {name}",
  "🌧️ {name}: Aankhon Mein Baarish, Dil Mein Toofan!",
  "🍂 {name}: Ab Kisi Se Koi Umeed Nahi Hai!",
  "🌑 Andhera Hi Sukoon Hai... - {name}",

  // --- ⚡ SHORT & UNIQUE ---
  "⚡ {name} | Dreamer | Achiever",
  "🌈 Stay Gold ✨ - {name}",
  "🍀 Lucky To Be {name}!",
  "💎 Rare Diamond: {name}",
  "🧿 Buri Nazar Wale... Tera Mooh Kaala! - {name}",
  "🔥 {name} 100% Original Content",
  "🕶️ Classy, Sassy & A Bit Badassy - {name}",
  "🎵 Music Lover | {name} | Foodie",
  "🎮 {name} - Level Up Every Day!",
  "📸 Capturing Moments... {name}",

  // --- 🔥 ATTITUDE SHAYARI (Extra 50+) ---
  "🔥 {name}: Humse Jalne Wale, Jalkar Raakh Ho Gaye!",
  "💪 Zid Hai Toh Jeet Hai... {name}",
  "🚫 No Love, No Tension... Only {name} Swag!",
  "👑 King Of My Own World - {name}",
  "👊 Baap Ke Saamne Ayyashi Aur {name} Ke Saamne Badmashi Mat Kar!",
  "🦁 King Is Always King, Whether It's {name} or Lion!",
  "👑 {name}: Badshah Nahi, Bazigar Hain Hum!",
  "💥 Entry Late Hogi Par Sabse Great Hogi - {name}",
  "😎 {name}: Style Aisa Ki Log Dekhte Reh Jayein!",
  "🚫 Faltu Logon Ke Liye Time Nahi Hai - {name}",
  "🔥 {name}: Sher Ka Baccha Akela Hi Achha!",
  "🕶️ {name}: Attitude Ki Pathshala Ka Monitor!",
  "💸 Paisa Toh Sab Kamate Hain, {name} Izat Kamata Hai!",
  "👑 Ruler Of Hearts - {name}",
  "🦁 {name} Naam Nahi, Brand Hai!",
  "👊 Humse Panga Mat Le, Warna {name} Danga Kar Dega!",
  "🕶️ {name} | Simple But Significant",
  "🔥 Apni Marzi Ka Maalik - {name}",
  "🦁 {name}: Jungli Sher, Bekhauf Jigar!",
  "💯 Real Since Birth - {name}",
  "🚫 Don't Judge {name} By His Silence!",
  "👑 {name}: Sabka Baap!",
  "🔥 Burn Your Ego, Not {name}!",
  "😎 {name}: High Rated Gabru!",
  "🕶️ Swag Ka Deewana - {name}",
  "🦁 {name}: Jigar Wala Banda!",
  "👊 {name}: Dushmano Ka Kaal!",
  "🔥 {name}: Aag Laga Dene Wala!",
  "👑 Unique Personality - {name}",
  "🦁 {name}: One Man Army!",
  "💯 100% Pure Attitude - {name}",
  "🚫 Limited Edition - {name}",
  "👑 {name}: Dil Ka Ameer!",
  "🔥 {name}: Fire On Ice!",
  "😎 {name}: Stylish Munda!",
  "🕶️ {name}: Rockstar!",
  "🦁 {name}: Tiger Zinda Hai!",
  "👊 {name}: Khatron Ka Khiladi!",
  "🔥 {name}: Dynamite!",
  "👑 {name}: Royal Blood!",
  "💯 {name}: Pure Soul!",
  "🚫 No Entry For Haters - {name}",
  "👑 {name}: Legend!",
  "🔥 {name}: Mastermind!",
  "😎 {name}: Smarty!",
  "🕶️ {name}: Cool Dude!",
  "🦁 {name}: Lion King!",
  "👊 {name}: Powerhouse!",
  "🔥 {name}: Flash!",
  "👑 {name}: Emperor!",
  "💯 {name}: Perfectionist!",
  "🚫 Only Respect For {name}!",
  "👑 {name}: Visionary!",
  "🔥 {name}: Trailblazer!",
  "😎 {name}: Trendsetter!",
  "🕶️ {name}: Icon!",
  "🦁 {name}: Alpha!",
  "👊 {name}: Warrior!",
  "🔥 {name}: Phoenix!",
  "👑 {name}: Majesty!",
  "💯 {name}: Authentic!"
];

